// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeter.proto

package greeter

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 定义请求结构
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 定义响应接口
type HelloReply struct {
	ReplyValue1          string   `protobuf:"bytes,1,opt,name=replyValue1,proto3" json:"replyValue1,omitempty"`
	ReplyValue2          string   `protobuf:"bytes,2,opt,name=replyValue2,proto3" json:"replyValue2,omitempty"`
	ReplyValue3          string   `protobuf:"bytes,3,opt,name=replyValue3,proto3" json:"replyValue3,omitempty"`
	ReplyValue4          string   `protobuf:"bytes,4,opt,name=replyValue4,proto3" json:"replyValue4,omitempty"`
	ReplyValue5          string   `protobuf:"bytes,5,opt,name=replyValue5,proto3" json:"replyValue5,omitempty"`
	ReplyValue6          string   `protobuf:"bytes,6,opt,name=replyValue6,proto3" json:"replyValue6,omitempty"`
	ReplyValue7          string   `protobuf:"bytes,7,opt,name=replyValue7,proto3" json:"replyValue7,omitempty"`
	ReplyValue8          string   `protobuf:"bytes,8,opt,name=replyValue8,proto3" json:"replyValue8,omitempty"`
	ReplyValue9          string   `protobuf:"bytes,9,opt,name=replyValue9,proto3" json:"replyValue9,omitempty"`
	ReplyValue10         string   `protobuf:"bytes,10,opt,name=replyValue10,proto3" json:"replyValue10,omitempty"`
	ReplyValue11         string   `protobuf:"bytes,11,opt,name=replyValue11,proto3" json:"replyValue11,omitempty"`
	ReplyValue12         string   `protobuf:"bytes,12,opt,name=replyValue12,proto3" json:"replyValue12,omitempty"`
	ReplyValue13         string   `protobuf:"bytes,13,opt,name=replyValue13,proto3" json:"replyValue13,omitempty"`
	ReplyValue14         string   `protobuf:"bytes,14,opt,name=replyValue14,proto3" json:"replyValue14,omitempty"`
	ReplyValue15         string   `protobuf:"bytes,15,opt,name=replyValue15,proto3" json:"replyValue15,omitempty"`
	ReplyValue16         string   `protobuf:"bytes,16,opt,name=replyValue16,proto3" json:"replyValue16,omitempty"`
	ReplyValue17         string   `protobuf:"bytes,17,opt,name=replyValue17,proto3" json:"replyValue17,omitempty"`
	ReplyValue18         string   `protobuf:"bytes,18,opt,name=replyValue18,proto3" json:"replyValue18,omitempty"`
	ReplyValue19         string   `protobuf:"bytes,19,opt,name=replyValue19,proto3" json:"replyValue19,omitempty"`
	ReplyValue20         string   `protobuf:"bytes,20,opt,name=replyValue20,proto3" json:"replyValue20,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetReplyValue1() string {
	if m != nil {
		return m.ReplyValue1
	}
	return ""
}

func (m *HelloReply) GetReplyValue2() string {
	if m != nil {
		return m.ReplyValue2
	}
	return ""
}

func (m *HelloReply) GetReplyValue3() string {
	if m != nil {
		return m.ReplyValue3
	}
	return ""
}

func (m *HelloReply) GetReplyValue4() string {
	if m != nil {
		return m.ReplyValue4
	}
	return ""
}

func (m *HelloReply) GetReplyValue5() string {
	if m != nil {
		return m.ReplyValue5
	}
	return ""
}

func (m *HelloReply) GetReplyValue6() string {
	if m != nil {
		return m.ReplyValue6
	}
	return ""
}

func (m *HelloReply) GetReplyValue7() string {
	if m != nil {
		return m.ReplyValue7
	}
	return ""
}

func (m *HelloReply) GetReplyValue8() string {
	if m != nil {
		return m.ReplyValue8
	}
	return ""
}

func (m *HelloReply) GetReplyValue9() string {
	if m != nil {
		return m.ReplyValue9
	}
	return ""
}

func (m *HelloReply) GetReplyValue10() string {
	if m != nil {
		return m.ReplyValue10
	}
	return ""
}

func (m *HelloReply) GetReplyValue11() string {
	if m != nil {
		return m.ReplyValue11
	}
	return ""
}

func (m *HelloReply) GetReplyValue12() string {
	if m != nil {
		return m.ReplyValue12
	}
	return ""
}

func (m *HelloReply) GetReplyValue13() string {
	if m != nil {
		return m.ReplyValue13
	}
	return ""
}

func (m *HelloReply) GetReplyValue14() string {
	if m != nil {
		return m.ReplyValue14
	}
	return ""
}

func (m *HelloReply) GetReplyValue15() string {
	if m != nil {
		return m.ReplyValue15
	}
	return ""
}

func (m *HelloReply) GetReplyValue16() string {
	if m != nil {
		return m.ReplyValue16
	}
	return ""
}

func (m *HelloReply) GetReplyValue17() string {
	if m != nil {
		return m.ReplyValue17
	}
	return ""
}

func (m *HelloReply) GetReplyValue18() string {
	if m != nil {
		return m.ReplyValue18
	}
	return ""
}

func (m *HelloReply) GetReplyValue19() string {
	if m != nil {
		return m.ReplyValue19
	}
	return ""
}

func (m *HelloReply) GetReplyValue20() string {
	if m != nil {
		return m.ReplyValue20
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "greeter.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "greeter.HelloReply")
}

func init() { proto.RegisterFile("greeter.proto", fileDescriptor_e585294ab3f34af5) }

var fileDescriptor_e585294ab3f34af5 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0xd3, 0x3d, 0x4f, 0xf3, 0x40,
	0x10, 0x04, 0xe0, 0x37, 0x2f, 0x49, 0x9c, 0x5c, 0x1c, 0x3e, 0x2e, 0x20, 0x8d, 0xa8, 0x22, 0x57,
	0x54, 0x91, 0x7d, 0xfe, 0xae, 0x29, 0xa0, 0x0e, 0x12, 0xbd, 0x91, 0x4e, 0x34, 0x07, 0x36, 0xc6,
	0x29, 0xfc, 0x17, 0xf9, 0x55, 0x08, 0x63, 0x24, 0xdf, 0x5c, 0xb7, 0x3b, 0x7a, 0xaa, 0xd5, 0x8e,
	0xd8, 0xbe, 0xb6, 0x5a, 0x77, 0xba, 0x3d, 0x34, 0x6d, 0xdd, 0xd5, 0xd2, 0x1b, 0xd7, 0x20, 0x10,
	0xfe, 0xa3, 0x36, 0xa6, 0x3e, 0xea, 0x8f, 0x93, 0xfe, 0xec, 0xa4, 0x14, 0xf3, 0xf7, 0xea, 0x4d,
	0x63, 0xb6, 0x9f, 0xdd, 0xad, 0x8f, 0xc3, 0x1c, 0x7c, 0x2d, 0x84, 0x18, 0x51, 0x63, 0x7a, 0xb9,
	0x17, 0x9b, 0xf6, 0x67, 0x78, 0xae, 0xcc, 0x49, 0x47, 0xa3, 0x9c, 0x46, 0xb6, 0x50, 0xf8, 0xcf,
	0x42, 0xd9, 0x22, 0xc6, 0x19, 0x8b, 0xd8, 0x16, 0x09, 0xe6, 0x2c, 0x12, 0x5b, 0xa4, 0x58, 0xb0,
	0x48, 0x6d, 0x91, 0x61, 0xc9, 0x22, 0xb3, 0x45, 0x0e, 0x8f, 0x45, 0x6e, 0x8b, 0x02, 0x2b, 0x16,
	0x85, 0x2d, 0x4a, 0xac, 0x59, 0x94, 0x32, 0x10, 0xfe, 0xe4, 0x3c, 0x21, 0xc4, 0x40, 0xac, 0x8c,
	0x4c, 0x84, 0x8d, 0x63, 0x22, 0x32, 0x0a, 0xbe, 0x63, 0x14, 0x99, 0x18, 0x5b, 0xc7, 0xc4, 0x64,
	0x12, 0x9c, 0x3b, 0x26, 0x21, 0x93, 0xe2, 0xc2, 0x31, 0x29, 0x99, 0x0c, 0x97, 0x8e, 0xc9, 0xc8,
	0xe4, 0xb8, 0x72, 0x4c, 0x4e, 0xa6, 0x80, 0x74, 0x4c, 0x41, 0xa6, 0xc4, 0xce, 0x31, 0x74, 0x67,
	0x15, 0xe2, 0x9a, 0x8d, 0x0a, 0xd5, 0xbd, 0xf0, 0x1e, 0x7e, 0x7f, 0x5f, 0x16, 0x62, 0xf5, 0x54,
	0xf5, 0xc3, 0x67, 0xcb, 0x9b, 0xc3, 0x5f, 0x41, 0xa6, 0x75, 0xb8, 0xdd, 0x71, 0xdc, 0x98, 0x3e,
	0xf8, 0xf7, 0xb2, 0x1c, 0x5a, 0x14, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x70, 0x45, 0x16, 0x87,
	0x56, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// 定义Greeter中SayHello方法
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/greeter.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// 定义Greeter中SayHello方法
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greeter.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greeter.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greeter.proto",
}
